language: java

install: mvn dependency:resolve

addons:
  sonarcloud:
    organization: "ryenus-github"

script:
  #- sonar-scanner
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=ryenus_rop

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.m2'
